name: Code Quality tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project

    - name: run goimports
      run: goimports -l .

  check-vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project

    - name: run vet
      run: go vet ./...

  check-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project

    - name: run golangci-lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9

  check-cyclo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project

    - name: run gocyclo
      run: gocyclo -over 30 .

  tests:
    runs-on: ubuntu-latest
    needs: [check-formatting, check-vet, check-lint, check-cyclo]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project

    - name: run tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project

    - name: build project
      run: go build

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project

    - name: run e2e
      run: npm run e2e
