name: Code Quality tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: "1.23.6"

    - name: install goimports
      run: go install golang.org/x/tools/cmd/goimports@v0.30.0

    - name: run goimports
      run: goimports -l .

  check-vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: "1.23.6"

    - name: install templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.833

    - name: generate code
      run: go generate

    - name: run vet
      run: go vet ./...

  check-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: "1.23.6"

    - name: install templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.833

    - name: generate code
      run: go generate

    - name: run golangci-lint
      uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837

  check-cyclo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: "1.23.6"

    - name: install gocyclo
      run: go install github.com/fzipp/gocyclo/cmd/gocyclo@v0.6.0

    - name: run gocyclo
      run: gocyclo -over 30 .

  tests:
    runs-on: ubuntu-latest
    needs: [check-formatting, check-vet, check-lint, check-cyclo]
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: "1.23.6"

    - name: install templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.833

    - name: generate code
      run: go generate

    - name: run tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: "1.23.6"

    - name: install templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.833

    - name: generate code
      run: go generate

    - name: build project
      run: go build

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: "1.23.6"

    - name: setup system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --allow-downgrades \
          nodejs=18.19.1* \
          npm=9.2.0* \
          libgtk2.0-0t64=2.24.33* \
          libgtk-3-0t64=3.24.41* \
          libgbm-dev=24.0.5* \
          libgbm1=24.0.5* \
          libnotify-dev=0.8.3* \
          libnss3=2:3.98* \
          libxss1=1:1.2.3* \
          libasound2t64=1.2.11* \
          libxtst6=2:1.2.3* \
          xauth=1:1.1.2* \
          xvfb=2:21.1.12*

    - name: install templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.833

    - name: run e2e
      run: npm run e2e
